# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('sysname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('community', models.CharField(max_length=30)),
                ('sysdescr', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=100)),
                ('hardware', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('uptime', models.IntegerField()),
                ('last_polled', models.DateTimeField()),
            ],
        ),
    ]
