# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='device',
            name='community',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='device',
            name='hardware',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_polled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='sysdescr',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='device',
            name='sysname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='uptime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
