# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20160309_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='sysdescr',
        ),
        migrations.RemoveField(
            model_name='device',
            name='version',
        ),
        migrations.AddField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
