# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20160310_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='community',
            field=models.CharField(blank=True, default='public', max_length=40, verbose_name='SNMP Community'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=128, unique=True, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
