# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20160310_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
