# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDN_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='Hostname')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP Address')),
                ('ip_conn', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('port', models.IntegerField(blank=True, null=True)),
                ('hw_address', models.CharField(blank=True, max_length=20)),
                ('date_start_conn', models.DateField(blank=True, null=True)),
                ('time_start_conn', models.TimeField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('device_type', models.CharField(blank=True, max_length=60)),
                ('protocol_vers', models.FloatField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=30)),
                ('config', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('curr_features', models.CharField(blank=True, max_length=150)),
                ('advert_features', models.CharField(blank=True, max_length=150)),
                ('supp_features', models.CharField(blank=True, max_length=150)),
                ('peer_features', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SDN_Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Interface Name')),
                ('hw_address', models.CharField(blank=True, max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('tx_bytes', models.IntegerField(blank=True, null=True)),
                ('rx_bytes', models.IntegerField(blank=True, null=True)),
                ('tx_packets', models.IntegerField(blank=True, null=True)),
                ('rx_packets', models.IntegerField(blank=True, null=True)),
                ('dropped', models.IntegerField(blank=True, null=True)),
                ('errored', models.IntegerField(blank=True, null=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.SDN_Device')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
