# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20160314_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdn_device',
            name='last_polled',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 14, 6, 36, 6, 517491, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
