# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20160422_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='icon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
