# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20160422_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cust_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
