# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_cust_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdn_port',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='advert_features',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='config',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='curr_features',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='date_start_conn',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='hw_address',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='ip_conn',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='last_polled',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='peer_features',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='port',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='protocol_vers',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='supp_features',
        ),
        migrations.RemoveField(
            model_name='sdn_device',
            name='time_start_conn',
        ),
        migrations.DeleteModel(
            name='SDN_Port',
        ),
    ]
